// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hLokpG4T8v3RHXkmw5LK_PL1cWM2l80',
    appId: '1:598385541518:web:5e1acb564113f95b7d64df',
    messagingSenderId: '598385541518',
    projectId: 'users-b4361',
    authDomain: 'users-b4361.firebaseapp.com',
    storageBucket: 'users-b4361.appspot.com',
    measurementId: 'G-CEW4ESESZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGtsnlqlPQOjuvk0giiZydUnhQMwjboY',
    appId: '1:598385541518:android:6fba78bb96c8b3167d64df',
    messagingSenderId: '598385541518',
    projectId: 'users-b4361',
    storageBucket: 'users-b4361.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmlh68C_TqfJgqN_KZVh85aoghOKfdUOs',
    appId: '1:598385541518:ios:8d3a71134bdafbf77d64df',
    messagingSenderId: '598385541518',
    projectId: 'users-b4361',
    storageBucket: 'users-b4361.appspot.com',
    iosBundleId: 'com.example.langspeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmlh68C_TqfJgqN_KZVh85aoghOKfdUOs',
    appId: '1:598385541518:ios:8d3a71134bdafbf77d64df',
    messagingSenderId: '598385541518',
    projectId: 'users-b4361',
    storageBucket: 'users-b4361.appspot.com',
    iosBundleId: 'com.example.langspeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1hLokpG4T8v3RHXkmw5LK_PL1cWM2l80',
    appId: '1:598385541518:web:3898cec83a29f5847d64df',
    messagingSenderId: '598385541518',
    projectId: 'users-b4361',
    authDomain: 'users-b4361.firebaseapp.com',
    storageBucket: 'users-b4361.appspot.com',
    measurementId: 'G-LQEW8KJNH5',
  );

}